services:
  db:
    image: postgres:15.5
    container_name: local_postgres_referencease_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: referencease