@startuml
'https://plantuml.com/component-diagram
'skinparam linetype ortho
skinparam linetype polyline


[Frontend] as FE
interface " " as FEGET

[Backend] as BE
interface " " as OfferBE
'interface "Read" as TakeBE


FE --d--( OfferBE : Read
FE -d- FEGET
'FE -d- TakeBE

BE --u--( FEGET : take
BE -u- OfferBE :offer
'BE -u- TakeBE



'
'SELECT ..> TakeBE : <<call>>
'OfferBE ..> IUD : <<call>>

@enduml